export const WOMEN = [
  {
    id: 1,
    index: "anya",
    name: "Аня",
    photos: ["1.webp", "3.webp", "4.webp", "5.webp", "6.webp", "8.webp"],
  },
  {
    id: 2,
    index: "karina",
    name: "Карина",
    photos: ["1.webp", "2.webp", "3.webp", "4.webp", "5.webp", "6.webp"],
  },
  {
    id: 3,
    index: "alisha",
    name: "Алиша",
    photos: [
      "1.png",
      "2.png",
      "3.png",
      "4.png",
      "5.png",
      "6.png",
      "7.png",
      "8.png",
      "9.png",
      "10.png",
      "11.png",
      "12.png",
      "13.png",
      "14.png",
      "15.png",
      "16.png",
      "17.png",
      "18.png",
      "19.png",
      "20.png",
      "21.png",
      "22.png",
      "23.png",
      "24.png",
    ],
  },
];

export const MEN = [
  {
    id: 1,
    index: "fernando",
    name: "Фернандо",
    photos: ["1.webp", "3.webp", "4.webp", "5.webp"],
  },

  {
    id: 2,
    index: "vladimir",
    name: "Владимир",
    photos: [
      "1.webp",
      "2.webp",
      "5.webp",
      "4.webp",
      "6.webp",
      "7.webp",
      "8.webp",
      "9.webp",
    ],
  },
];
