import { PromptBookRaw } from "@/components/types";

export const PROMTBOOKS: Record<string, PromptBookRaw> = {
  "50-high-fashion-editorial-prompts-vol-1": {
    id: 1,
    gumroadSlug: "50-ai-fashion-editorial-prompts-vol1",
    number: 50,
    links: {
      cm: "https://creativemarket.com/AlenaMurasheva/291838555-50-High-Fashion-Editorial-Prompts-V1",
    },
    mainCategory: "fashion",
    tags: ["fashion", "women"],
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },

  "50-high-fashion-editorial-prompts-vol-2": {
    id: 5,
    gumroadSlug: "50-ai-fashion-editorial-prompts-vol2",
    boostyId: "40f7cb76-5db0-419a-b3f5-55a640de03f9",
    number: 50,
    isBestseller: true,
    links: {
      cm: "https://creativemarket.com/AlenaMurasheva/291894652-50-High-Fashion-Editorial-Prompts-V2",
    },
    mainCategory: "fashion",
    tags: ["fashion", "women"],
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  },
  "50-high-fashion-editorial-prompts-vol-3": {
    id: 27,
    gumroadSlug: "50-ai-fashion-editorial-prompts-vol3",
    number: 50,
    mainCategory: "fashion",
    tags: ["fashion", "women"],
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  },

  "50-men-fashion-editorial-prompts-vol-1": {
    id: 3,
    gumroadSlug: "50-men-fashion-editorial-prompts-vol-1",
    number: 50,
    tags: ["fashion", "men"],
    mainCategory: "fashion",
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },

  "50-men-fashion-editorial-prompts-vol-2": {
    id: 42,
    gumroadSlug: "50-men-fashion-editorial-prompts-vol-2",
    number: 50,
    tags: ["fashion", "men"],
    mainCategory: "fashion",
    type: "pack",
    images: [1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13],
  },

  "50-ideal-skin-midjourney-prompts-vol-1": {
    id: 4,
    gumroadSlug: "50-ideal-skin-midjourney-prompts-beauty",
    boostyId: "6801a414-dcef-46b9-9af5-4700e229ac12",
    number: 50,
    links: {
      cm: "https://creativemarket.com/AlenaMurasheva/291851819-50-Ideal-Skin-Midjourney-Prompts-V.1",
    },
    isBestseller: true,
    tags: ["beauty"],
    mainCategory: "beauty",
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },

  "50-jewelry-product-photo-ai-prompts": {
    id: 6,
    gumroadSlug: "50-ai-jewelry-photography-prompts",
    number: 50,
    tags: ["jewelry", "product"],
    mainCategory: "product",
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },

  "24-ai-maternity-photoshoot-prompts": {
    id: 7,
    gumroadSlug: "24-ai-maternity-photoshoot-prompts",
    boostyId: "4f29f408-09e8-4e27-b308-84fcee7c2de2",
    number: 24,
    isBestseller: true,
    tags: ["fashion", "women", "maternity"],
    mainCategory: "fashion", // TODO?
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8],
  },

  "32-business-man-photo-prompts": {
    id: 24,
    gumroadSlug: "32-business-man-photo-prompts",
    number: 32,
    tags: ["business", "men"],
    mainCategory: "business",
    type: "pack",
    images: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  },

  "30-christmas-woman-photo-prompts": {
    id: 8,
    gumroadSlug: "30-christmas-woman-photo-prompts",
    number: 30,
    tags: ["christmas", "women"],
    mainCategory: "christmas",
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8],
  },

  "40-christmas-kids-photo-prompts-ai": {
    id: 9,
    gumroadSlug: "40-christmas-kids-ai-photo-prompts",
    number: 40,
    tags: ["christmas", "kids"],
    mainCategory: "christmas",
    type: "pack",
    images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },

  "30-business-woman-photo-prompts-ai": {
    id: 10,
    gumroadSlug: "30-ai-business-woman-photo-prompts",
    boostyId: "796a8676-c1e8-4ee7-9c6f-0f4ad6c29a48",
    number: 30,
    tags: ["business", "women"],
    mainCategory: "business",
    type: "pack",
    images: [1, 3, 4, 6, 7, 8, 9, 10],
  },

  "60-fantasy-photo-prompts-ai-portrait": {
    id: 11,
    gumroadSlug: "60-fantasy-portrait-ai-prompts-character",
    number: 60,
    tags: ["fantasy"],
    mainCategory: "fantasy",
    type: "pack",
    images: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  },

  "25-wizard-school-photo-prompts-ai": {
    id: 12,
    gumroadSlug: "25-wizard-school-ai-photo-prompts",
    number: 25,
    tags: ["fantasy"],
    mainCategory: "fantasy",
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  },

  "15-ai-women-headshot-prompts-professional": {
    id: 15,
    gumroadSlug: "15-ai-women-headshot-prompts",
    boostyId: "7fe0af5d-fcba-4346-8e65-39963eb91e60",
    number: 15,
    tags: ["business", "women", "headshot"],
    mainCategory: "business",
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 20, 21],
  },
  "ai-photo-prompts-30-woman-work-lifestyle": {
    id: 14,
    gumroadSlug: "30-woman-work-lifestyle-prompts",
    number: 30,
    links: {
      cm: "https://creativemarket.com/AlenaMurasheva/291933545-Woman-Work-Lifestyle-Photo-Prompts",
    },
    tags: ["business", "women", "lifestyle"],
    mainCategory: "business",
    type: "pack",
    images: [1, 3, 4, 17, 18, 19, 20, 21, 22],
  },

  "faceless-aesthetic-100-ai-photo-prompts": {
    id: 39,
    gumroadSlug: "faceless-aesthetic-100-ai-photo-prompts",
    number: 100,
    tags: ["lifestyle"],
    mainCategory: "lifestyle",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 5, 6, 7, 8],
  },

  "50-old-money-ai-photo-prompts-vol1": {
    id: 16,
    gumroadSlug: "50-old-money-ai-photo-prompts-vol1",
    number: 50,
    tags: ["fashion", "women", "lifestyle"],
    mainCategory: "lifestyle",
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  },

  "50-old-money-ai-photo-prompts-vol2": {
    id: 17,
    gumroadSlug: "50-old-money-ai-photo-prompts-vol2",
    number: 50,
    tags: ["fashion", "women", "lifestyle"],
    mainCategory: "lifestyle",
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  },

  "22-business-man-headshot-prompts-ai": {
    id: 18,
    gumroadSlug: "22-business-man-headshot-prompts",
    boostyId: "b8a6673e-ff54-4121-99ec-99bd57c92031",
    number: 22,
    isBestseller: true,
    tags: ["business", "men", "headshot"],
    mainCategory: "business",
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  },

  "40-muslim-women-business-photo-prompts": {
    id: 19,
    gumroadSlug: "40-ai-muslim-women-business-photo",
    number: 40,
    tags: ["business", "women"],
    mainCategory: "business",
    type: "pack",
    images: [1, 3, 4, 5, 6, 7, 8, 9, 21, 22, 23, 24, 25],
  },

  "8-red-carpet-couple-ai-photo-prompts": {
    id: 22,
    gumroadSlug: "8-red-carpet-couple-ai-photo-prompts",
    number: 8,
    tags: ["red_carpet", "men", "women"],
    mainCategory: "red_carpet",
    type: "pack",
    images: [1, 2, 3, 4, 5],
  },

  "8-red-carpet-men-photo-prompts-ai": {
    id: 20,
    gumroadSlug: "8-red-carpet-men-photo-prompts",
    number: 8,
    links: {},
    tags: ["red_carpet", "men"],
    mainCategory: "red_carpet",
    type: "pack",
    images: [1, 2, 3, 4, 5],
  },

  "8-red-carpet-women-photo-prompts": {
    id: 21,
    gumroadSlug: "8-red-carpet-women-ai-photo-prompts",
    number: 8,
    tags: ["red_carpet", "women"],
    mainCategory: "red_carpet",
    type: "pack",
    images: [1, 2, 3, 4, 5],
  },

  "35-cosmetic-product-photo-prompts": {
    id: 23,
    gumroadSlug: "35-cosmetic-product-photo-prompts",
    boostyId: "19a1dd70-bd6b-4624-a662-706574bf40a5",
    number: 35,
    isBestseller: true,
    tags: ["cosmetic", "product"],
    mainCategory: "product",
    type: "pack",
    images: [2, 4, 5, 6, 7, 8, 9, 10, 11],
  },

  "75-cosmetic-product-photo-prompts": {
    id: 25,
    gumroadSlug: "75-cosmetic-product-photo-prompts",
    number: 75,
    tags: ["cosmetic", "product"],
    mainCategory: "product",
    type: "pack",
    images: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  },
  "8-advertising-photo-prompts-vol-1": {
    id: 26,
    gumroadSlug: "8-advertising-photo-prompts",
    number: 8,
    tags: ["fantasy"],
    mainCategory: "fantasy",
    type: "pack",
    images: [1, 2, 3, 4, 5],
  },

  "realistic-ai-influencer-prompts": {
    id: 28,
    gumroadSlug: "realistic-ai-influencer-prompts",
    boostyId: "e0b0dbee-8d7e-47f1-bc7b-8299b85ca2f5",
    number: 200,
    isBestseller: true,
    tags: ["lifestyle", "women", "avatar"],
    mainCategory: "avatar",
    type: "pack",
    fileType: "link",
    images: [1, 2, 3, 4, 5, 6, 8],
  },

  "women-fashion-editorial-prompts-bundle": {
    id: 29,
    gumroadSlug: "women-fashion-editorial-prompts-bundle",
    number: 150,
    pack: [1, 5, 27],
    tags: ["fashion", "women"],
    type: "bundle",
    images: [0, 1, 2, 3],
  },

  "250-fashion-editorial-prompts-bundle": {
    id: 45,
    gumroadSlug: "250-fashion-editorial-prompts-bundle",
    number: 250,
    pack: [1, 5, 27, 3, 42],
    tags: ["fashion", "women", "men"],
    type: "bundle",
    images: [0, 1, 2, 3, 4, 5],
  },
  "business-men-prompts-bundle": {
    id: 30,
    gumroadSlug: "business-men-prompts-bundle",
    number: 54,
    pack: [24, 18],
    links: {},
    tags: ["business", "men"],
    type: "bundle",
    images: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  "business-women-prompts-bundle": {
    id: 31,
    gumroadSlug: "business-women-prompts-bundle",
    number: 75,
    pack: [10, 15, 14],
    tags: ["business", "women"],
    type: "bundle",
    images: [0, 1, 2, 3, 4, 5, 6],
  },
  "red-carpet-prompts-bundle": {
    id: 32,
    gumroadSlug: "red-carpet-prompts-bundle",
    number: 24,
    pack: [22, 21, 20],
    links: {},
    tags: ["red_carpet"],
    type: "bundle",
    images: [0, 1, 2, 3],
  },
  "120-product-podiums-photo-prompts": {
    id: 34,
    gumroadSlug: "120-product-podiums-photo-prompts",
    number: 120,
    tags: ["product"],
    mainCategory: "product",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 5, 6, 7, 8],
  },

  // "32-monochromatic-studio-portrait-prompt-pack": {
  //   id: 35,
  //   gumroadSlug: "32-monochromatic-studio-portrait-prompt-pack",
  //   name: "32 Monochromatic Studio Portrait Prompt Pack",
  //   number: 32,
  //   tags: ["studio"],
  //   mainCategory: "studio",
  //   type: "pack",
  //   fileType: "link",
  //   images: [1, 3, 4, 5, 6, 7],
  //   summary:
  //     "Monochromatic Studio Portrait Prompt Pack is a curated collection of 32 carefully crafted photo prompts designed for realistic, modern studio portraits in a single color palette.",
  //   text: t35,
  // },

  "120-white-frame-interior-mockup-prompts": {
    id: 36,
    gumroadSlug: "120-white-frame-interior-mockup-prompts",
    number: 120,
    tags: ["product"],
    mainCategory: "product",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 5, 6, 7, 8],
  },

  "16-red-backdrop-studio-photo-prompts": {
    id: 37,
    gumroadSlug: "16-red-backdrop-studio-photo-prompts",
    number: 16,
    tags: ["studio"],
    mainCategory: "studio",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 5],
  },
  "16-valentines-day-women-photo-prompts": {
    id: 38,
    gumroadSlug: "16-valentines-day-women-photo-prompts",
    number: 16,
    tags: ["women", "fashion"],
    mainCategory: "fashion",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 5],
  },
  "25-creative-portraits-photo-prompts": {
    id: 40,
    gumroadSlug: "25-creative-portraits-photo-prompts",
    number: 25,
    tags: ["fashion"],
    mainCategory: "fashion",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 5, 6],
    price: {
      ru: 1000,
      en: 18,
    },
  },
  "cartoon-style-image-prompts": {
    id: 44,
    gumroadSlug: "cartoon-style-image-prompts",
    number: 10,
    tags: ["design"],
    mainCategory: "design",
    type: "pack",
    fileType: "link",
    images: [1, 2, 3],
  },
  "studio-poses-photo-prompts": {
    id: 48,
    gumroadSlug: "studio-poses-photo-prompts",
    number: 55,
    tags: ["studio"],
    mainCategory: "studio",
    type: "pack",
    fileType: "link",
    images: [1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13],
  },

  "viral-image-prompts": {
    id: 49,
    isBestseller: true,
    gumroadSlug: "viral-image-prompts",
    number: 45,
    tags: ["fantasy", "design"],
    mainCategory: "fantasy",
    type: "pack",
    fileType: "link",
    images: [1, 3, 7, 8, 9, 10, 11, 12],
  },
  "ai-avatar-selfie-prompts": {
    id: 50,
    gumroadSlug: "ai-avatar-selfie-prompts",
    number: 25,
    tags: ["avatar", "lifestyle"],
    mainCategory: "avatar",
    type: "pack",
    fileType: "link",
    images: [1, 3, 5, 6, 7, 8],
  },
};
